# -*- coding: utf-8 -*-
"""basic_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a7Fb3WYGiHulEWbUgJBA5KjdfQT5Xaeq

Variáveis e Objetos
"""

#Cria variável do tipo inteiro
x = 1
print(x)

#Cria variaável do tipo float
y = 3.13
print(y)

#Criar variável do tipo String
m = "Python"
m = 'Python'
print(m)

#Criar variável do tipo lógica
w = True
y = False
print(y)

#Calculadora
x = 10
y = 20
z = 100
w = (x + y) * z / 100
print(w)

#Exibir texto no console
print("Este texto será impresso no console")
print(x)
print("Texto e duas variáveis: ", x , ", ", z)

#Verificar tipo
print(type(x))
print(type(m))

#Entrada de dados
print("Informe o valor: ")
i = input()
#Mostra tipo string
print(type(i))

#Entrada de valor com msg separada e junto
print("Informe o valor: ")
i = input()
#ou
i = input("Informe o valor: ")

#Conversão de valores
#para inteiro
var = input("Informe o valor: ")
print(type(var))
var = int(var)
print(type(var))

#para float
var = input("Informe o valor: ")
print(type(var))
var = float(var)
print(type(var))

# Este texto é um comentário
x = 10 # a partir daqui é um comentário